/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flappybird_java;

import java.net.URL;
import javax.swing.*;
import java.awt.*;

public class Main {
    private static Frame frame;
    public static void main(String[] args) {
        frame = new Frame();
    }

    public static URL getPath(String path) { // 절대 경로
        return Main.class.getResource(path);
    }

    public static Frame getFrame(){ // Frame에 대한 내용을 주는 함수
        return frame;
    }

    public static int Cilmp(int number, int min, int max){
        if (number < min){
            return min;
        }
        else if (number > max){
            return max;
        }
        return number;
    }
}
